---
  - name: install docker, docker-py, bridge-utils
    yum:
      name: "{{ item }}"
    with_items:
      - docker
      - python-docker-py
      - bridge-utils

  - name: configure custom registry
    lineinfile:
      dest: "/etc/sysconfig/docker"
      regexp: '^ADD_REGISTRY'
      line: "ADD_REGISTRY='--add-registry {{ docker_registry | default('0.0.0.0/0') }}'"

  - name: enable docker daemon
    service:
      name: docker
      enabled: yes

  - name: start the docker daemon
    service:
      name: docker
      state: restarted
